### ISSUE TITLE
'id<UINavigationControllerDelegate,UIImagePickerControllerDelegate> _Nullable' error

### ISSUE THREAD

**Issue by levilais** [yasirkula/UnityNativeGallery#187]
**Description of the bug**

The service works fine in UnityEditor but when I build to iOS, open the project in Xcode, and play the app it compiles til about 500 or so files and then hits this bug: 

Incompatible pointer types assigning to 'id<UINavigationControllerDelegate,UIImagePickerControllerDelegate> _Nullable' from 'Class'

When I comment it out, a few more pop up.  It appears to be an issue with the "imagePicker.delegate = self" on line 131.

The changes in my environment since it worked were upgrading Xcode (see below) and upgrading my iPad (see below).  My iPad is on iPadOS 14.6 and the Unity/iPad relationship worked yesterday so I think it's related to the new Xcode updates, but I'm not certain.

**Reproduction steps**

See above and below.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2019.4.20f1
- Platform: Running on a MacBook Pro MacOS Big Sur 11.3 Beta, Xcode 12.5 public, iOS device it's trying to build to is 14.5 public.
- How did you download the plugin: Asset Store.  I also realized it was an older version and updated to the latest release and got the same results.

**Additional info**
I'm also seeing "Use of undeclared identifier 'UnitySendMessage'" errors in a  few places in the same file - lines 117, 126, 260, 270, etc.

**Comment by taipvnb** [comment]
Same issue

**Comment by yasirkula** [comment]
You can't have this error in the newest version because I've replaced all problematic lines with `imagePickerNew.delegate = (id) self;` already. You should delete the plugin, reimport it, delete the previous Xcode build and then rebuild.

**Comment by rubit0** [comment]
Same issue here after updating Xcode to 12.5.

These steps fixed the problem:
- Delete the Xcode project
- Delete the existing UnityNativeGallery and UnityNativeCamera Plugins
- Import the latest versions of said plugings
- Make a new ios build
- Enjoy!

**Comment by clearsitedesigns** [comment]
The same issue, for 14.5

**Comment by yasirkula** [comment]
If you are getting the exact same error message, then:

> You can't have this error in the newest version because I've replaced all problematic lines with `imagePicker.delegate = (id) self;` already. You should delete the plugin, reimport it, delete the previous Xcode build and then rebuild.

**Comment by antonsem** [comment]
I'm having a similar error on filePicker.delegate = self; lines (25. and 56. lines) in xcode, in NativeFilePicker.mm file.
XCode version is 12.5 (12E262)
Unity version is 2020.3.0f1
I've downloaded the latest version from the asset store.

**Comment by antonsem** [comment]
Oh, it seems the problem was the lack of the cast! I've changed lines `filePicker.delegate = self` to `filePicker.delegate = (id)self`, and it worked!

**Comment by antonsem** [comment]
> 
> 
> If you are getting the exact same error message, then:
> 
> > You can't have this error in the newest version because I've replaced all problematic lines with `imagePicker.delegate = (id) self;` already. You should delete the plugin, reimport it, delete the previous Xcode build and then rebuild.

And it looks like before complaining I should carefully read the answers... Thanks for the great and fast support!

**Comment by yasirkula** [comment]
How could you have this issue if you've downloaded the latest version from Asset Store?
